## Just learning Numpy



In [1]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [6]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 2, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 12)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
import pandas as pd

df = pd.DataFrame(a2)

In [17]:
df

,0,1,2
0,1,2,3
1,4,5,6


In [18]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [25]:
ones = np.ones((2, 3, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
np.zeros((4, 4, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [29]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 3, 6, 5, 8],
       [2, 0, 4, 4, 6],
       [2, 1, 1, 1, 1]], dtype=int32)

In [30]:
np.random.random((5, 5))

array([[0.51830325, 0.06739763, 0.9947458 , 0.44261126, 0.89836892],
       [0.60288484, 0.82941073, 0.4549976 , 0.97867406, 0.39630811],
       [0.83480784, 0.47623952, 0.90742188, 0.39930314, 0.08428611],
       [0.26003726, 0.07885986, 0.82413245, 0.27165392, 0.09062578],
       [0.69729418, 0.47691242, 0.05497383, 0.53073416, 0.37770183]])

In [31]:
np.random.rand(5, 3)

array([[0.59954209, 0.78978514, 0.84548234],
       [0.83681207, 0.311553  , 0.25417819],
       [0.57920269, 0.80768434, 0.03996904],
       [0.27286865, 0.64689305, 0.75827975],
       [0.05504915, 0.84991351, 0.38810162]])

In [35]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [ ]:
np.random.seed(7)
random_array_5 = np.random.randint(10, size=(5, 3))
random_array_5
# random.seed() is used to set the seed for the random number generator, which ensures that the same random numbers are generated each time the code is run. This is useful for reproducibility in experiments and debugging.

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]], dtype=int32)